login:
    path:   /login
    defaults:  { _controller: ezpublish.security.controller:loginAction }
login_check:
    path:   /login_check
logout:
    path:   /logout

_ezpublishRoutes:
    resource: "@EzPublishCoreBundle/Resources/config/routing/internal.yml"

_ezpublishLegacyRoutes:
    resource: "@EzPublishLegacyBundle/Resources/config/routing.yml"

_ezpublishRestRoutes:
    resource: "@EzPublishRestBundle/Resources/config/routing.yml"
    prefix:   %ezpublish_rest.path_prefix%

_ezpublishRestOptionsRoutes:
    resource: "@EzPublishRestBundle/Resources/config/routing.yml"
    prefix: %ezpublish_rest.path_prefix%
    type: rest_options

_ezpublishDemoRoutes:
    resource: "@eZDemoBundle/Resources/config/routing.yml"

#Later for 5.4
#_ezpublishPlatformUIRoutes:
#    resource: "@eZPlatformUIBundle/Resources/config/routing.yml"


# sylius routing
# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_installer:
    resource: "@SyliusInstallerBundle/Resources/config/routing.yml"

sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
    prefix: /api

sylius_web:
    resource: "@SyliusWebBundle/Resources/config/routing/main.yml"